<?xml version="1.0"?>

<robot name="rover" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- параметры -->
    <xacro:property name="base_length"      value="0.6" />
    <xacro:property name="base_width"       value="0.4" />
    <xacro:property name="base_height"      value="0.2" />

    <xacro:property name="wheel_radius"     value="0.1" />
    <xacro:property name="wheel_width"      value="0.05"/>
    <xacro:property name="wheel_base"       value="0.4" />
    <xacro:property name="clearance"        value="0.1" />
    
    <xacro:property name="wheel_x_dist"     value="0.5" />
    <xacro:property name="wheel_y_dist"     value="0.5" />  <!--or wheel_separation-->
    
    <!-- визуальные материалы -->
    <material name="blue">
        <color rgba="0 0 0.8 1"/>
    </material>

    <!-- макрос для колеса -->
    <xacro:macro name="wheel" params="name x y z">
        <link name="${name}_link">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
                </geometry>

                <origin xyz="0 0 0" rpy="${pi/2} 0 0"/> <!-- поворот оси -->
            </visual>

            <collision>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
                </geometry>
                
                <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
            </collision>

            <inertial>
                <mass value="1"/>
                <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01"/>
            </inertial>
        </link>

        <joint name="${name}_joint" type="continuous">
            <parent link="base_link"/>
            <child link="${name}_link"/>
            <origin xyz="${x} ${y} ${z}" rpy="0 0 0"/>
            <axis xyz="0 1 0"/>
        </joint>
    </xacro:macro>


    <!-- база робота -->
    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>

            <material name="blue"/>
        </visual>

        <collision>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
        </collision>

        <inertial>gazebo --verbose
            <mass value="10"/>
            <inertia ixx="0.1" ixy="0.0" ixz="0.0" iyy="0.1" iyz="0.0" izz="0.1"/>
        </inertial>
    </link>

     <!-- установка колёс -->
    <xacro:wheel name="front_left"  x="${ wheel_x_dist/2}"  y="${-wheel_y_dist/2}" z="-${clearance}"/>
    <xacro:wheel name="front_right" x="${ wheel_x_dist/2}"  y="${ wheel_y_dist/2}" z="-${clearance}"/>
    <xacro:wheel name="back_left"   x="${-wheel_x_dist/2}"  y="${-wheel_y_dist/2}" z="-${clearance}"/>
    <xacro:wheel name="back_right"  x="${-wheel_x_dist/2}"  y="${ wheel_y_dist/2}" z="-${clearance}"/>


    <!-- ros2_control -->robot_description': Command(['xacro', ' ', rover_model_xacro])}
    <ros2_control name="RoverSystem" type="system">
        <hardware>
            <plugin>gazebo_ros2_control/GazeboROS2ControlPlugin</plugin>
        </hardware>

        <joint name="front_left_joint">
            <command_interface name="velocity"/>
            <state_interface   name="velocity"/>
            <state_interface   name="position"/>
        </joint>

        <joint name="front_right_joint">
            <command_interface name="velocity"/>
            <state_interface   name="velocity"/>
            <state_interface   name="position"/>
        </joint>

        <joint name="back_left_joint">
            <command_interface name="velocity"/>
            <state_interface   name="velocity"/>
            <state_interface   name="position"/>
        </joint>

        <joint name="back_right_joint">
            <command_interface name="velocity"/>
            <state_interface   name="velocity"/>
            <state_interface   name="position"/>
        </joint>
    </ros2_control>

    <!-- Gazebo plugin for ros2_control -->
    <gazebo>
        <plugin name="gazebo_ros2_control" filename="libgazebo_ros2_control.so"/>
    </gazebo>
</robot>

